### ISSUE TITLE
am I doing it wrong?

### ISSUE THREAD

**Issue by ralyodio** [umayr/koa2-kickstarter#3]
I ran `npm start` and went to http://localhost:4000 but I get a 404. am I doing it wrong? what should I see?

**Comment by umayr** [comment]
Its expected. As there is no route register to `/` location. You can try hitting `/user` as its being registered [here](https://github.com/umayr/koa2-kickstarter/blob/master/src/route/user.js#L7). Let me know if it doesn't work either.

**Comment by ralyodio** [comment]
That worked. you should put a "welcome" or something at /

**Comment by umayr** [comment]
Yeah. I definitely should.
